[settings]
disable_backends = ["asdf"]
minimum_release_age = "2d"

[settings.python]
compile = true
uv_venv_auto = "source"

[settings.npm]
package_manager = "pnpm"

[tools]
bottom = "latest"
btop = "latest"
claude = "latest"
cmake = "latest"
codex = "latest"
docker-cli = "latest"
docker-compose = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gdu = "latest"
go = ["1.26", "latest"]
jq = "latest"
lazygit = "latest"
lsd = "latest"
neovim = "latest"
ninja = "latest"
node = ["24", "lts"]
"npm:9router" = "latest"
"npm:@colbymchenry/codegraph" = "latest"
"npm:pm2" = "latest"
"npm:typescript" = "latest"
opencode = "latest"
"pipx:pre-commit" = { version = "latest", pipx_args = "--with pre-commit-uv --force-reinstall" }
"pipx:pyrefly" = "latest"
pnpm = "latest"
python = ["3.14", "3.12", "latest"]
ripgrep = "latest"
rtk = "latest"
ruff = "latest"
rust = ["1.95", "stable"]
rust-analyzer = "latest"
sccache = "latest"
shellcheck = "latest"
shfmt = "latest"
tlrc = { version = "latest", os = ["linux/amd64", "darwin", "windows"] }
tmux = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
